#!/bin/bash
# run_server - Start the Zypo Server Node (For hosting your domains remotely)

# Kill child processes on exit
trap "kill 0" EXIT

echo "Starting Server Node daemon (auto-restarting on .go/.html changes)..."

cd dot-zypo-server && npx nodemon --signal SIGTERM --watch . --watch ../dot-zypo-common --ignore data/ --ignore zypo_sites/ --ext go,html,css,json --exec "go run main.go"
