#!/bin/bash
# run_client - Start the Zypo Client Node

# Kill child processes on exit
trap "kill 0" EXIT

echo "Starting Client Node daemon (auto-restarting on .go/.html changes)..."

cd dot-zypo-client && npx nodemon --signal SIGTERM --watch . --watch ../dot-zypo-common --ignore data/ --ignore zypo_sites/ --ext go,html,css,json --exec "go run main.go"
